version: "3.9"

services:
  storefront:
    build:
      context: .
      args:
        - region=us-east-1
        - alice=0
    environment:
      - runtime_env=dev
  database:
    image: "mysql"
    volumes:
      - ./mysql:/var/lib/mysql:rw #Syntax: source:target:access_mode mounting volume from ./mysql in localhost to /var/lib/mysql in docker containers
      - kinetico:/var/lib/mysql
    env_file:
      - ./mysql/env_vars
volumes:
  kinetico: