---
- hosts: dbsystems
  become: yes
  vars:
    user: linuxthi
  tasks:
    - name: Ensure the user exists
      user:
        name: "{{ user }}"
        home: /home/{{ user }}
        state: present
        group: "{{ user }}"
    - name: Ensure a user can run sudo commands without a password
      lineinfile:
        path: /etc/sudoers
        line: present
        line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: Verify sudoers file
      command: visudo -cf /etc/sudoers
      register: output_status
      changed_when: false

    - name: print output
      debug:
        var: output_status.stdout_lines